url: "jdbc:mysql://localhost:3306/?autoReconnect=true"
user: "minecraft"
password: ""

updateFrequency: 5
speed: 1.0

videoPath: "./recordings/"
# in milliseconds: screen recorder recommends 50
captureInterval: 50
