main: de.saar.minecraft.replay.ReplayPlugin
name: ReplayPlugin
version: 1.0.0
description: Replays experiments from the database
api-version: 1.15
commands:
  select:
    description: Select a game to replay.
    usage: /select [game id]