main: de.saar.minecraft.replay.ReplayPlugin
name: ReplayPlugin
version: 1.0.0
description: Replays experiments from the database
api-version: 1.15
commands:
  connect:
    description: connects to the specified database
    usage: /connect [db]
  select:
    description: Select a game to replay.
    usage: /select [game id]
  record:
    description: Record a game during replay
    usage: /record [game id]
  stopRecording:
    description: Stop a recording
    usage: /stopRecording