updateFrequency: 5
fixedMaterials:
  - BEDROCK
  - GRASS
  - GRASS_BLOCK
  - DIRT
  - COARSE_DIRT
  - TNT
  - LAVA
  - WATER

clientPort: 2802

worldFilePath: /de/saar/minecraft/worlds/

startInventory:
  - STONE
  - RED_WOOL

NotBannedPlayers:
  - Minecraft_UdS_1
  - Minecraft_UdS_2
  - Minecraft_UdS_3
  - Minecraft_UdS_4
  - Minecraft_UdS_5
