updateFrequency: 5
fixedMaterials:
# ground layers
  - BEDROCK
  - LIME_CONCRETE
# blocks that change / cause others to change easily
  - GRASS
  - GRASS_BLOCK
  - DIRT
  - COARSE_DIRT
  - FARMLAND
  - GRASS_PATH
# potentially dangerous
  - TNT
  - LAVA
  - WATER


clientPort: 2802

worldFilePath: /de/saar/minecraft/worlds/

startInventory:
  - STONE
  - RED_WOOL

NotBannedPlayers:
  - Minecraft_UdS_1
  - Minecraft_UdS_2
  - Minecraft_UdS_3
  - Minecraft_UdS_4
  - Minecraft_UdS_5
