updateFrequency: 200
fixedMaterials:
  - BEDROCK
  - GRASS
  - GRASS_BLOCK
  - DIRT
  - COARSE_DIRT
  - TNT
  - LAVA
  - WATER
  - MISSPELLED_MATERIAL

clientPort: 2802

worldFilePath: /de/saar/minecraft/worlds/

startInventory:
  - STONE
  - BLUE_WOOL

NotBannedPlayers:
  - Minecraft_UdS_1
  - Minecraft_UdS_2
  - Minecraft_UdS_3
  - Minecraft_UdS_4
  - Minecraft_UdS_5
